# Cloudflare Workers configuration
name = "hn-summarizer"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Set the Workers runtime to nodejs

workers_dev = true

[[ d1_databases ]]
binding = "HN_SUMMARIZER_DB"
database_name = "hn-summarizer"
database_id = "<YOUR_DATABASE_ID>"  # Replace with your actual database ID# D1 Database binding

# R2 bucket binding
[[r2_buckets]]
binding = "CONTENT_BUCKET"
bucket_name = "hn-summarizer-content"
preview_bucket_name = "hn-summarizer-content-dev" # For local development

# Environment variables
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
MAX_STORIES_PER_FETCH = "30"
CONTENT_PROCESSOR_BATCH_SIZE = "10"
CONTENT_PROCESSOR_CONCURRENCY = "1"
SUMMARY_GENERATOR_BATCH_SIZE = "5"
SUMMARY_GENERATOR_CONCURRENCY = "3"
NOTIFICATION_SENDER_BATCH_SIZE = "5"
NOTIFICATION_SENDER_CONCURRENCY = "3"
SUMMARIZATION_MAX_TOKENS = "65536"  # Updated for Gemini 2.5 output token limit
MAX_RETRY_ATTEMPTS = "5"

# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
MAX_STORIES_PER_FETCH = "50"
CONTENT_PROCESSOR_BATCH_SIZE = "20"
CONTENT_PROCESSOR_CONCURRENCY = "1"
SUMMARY_GENERATOR_BATCH_SIZE = "5"
SUMMARY_GENERATOR_CONCURRENCY = "3"
NOTIFICATION_SENDER_BATCH_SIZE = "10"
NOTIFICATION_SENDER_CONCURRENCY = "3"
SUMMARIZATION_MAX_TOKENS = "65536"  # Updated for Gemini 2.5 output token limit
MAX_RETRY_ATTEMPTS = "5"

# D1 Database binding for production - duplicate the binding with the same values
[[ env.production.d1_databases ]]
binding = "HN_SUMMARIZER_DB"
database_name = "hn-summarizer"
database_id = "<YOUR_DATABASE_ID>"  # Replace with your actual database ID# D1 Database binding
# R2 bucket binding for production
[[env.production.r2_buckets]]
binding = "CONTENT_BUCKET"
bucket_name = "hn-summarizer-content"

# Secrets (to be set using 'wrangler secret put'):
# - GOOGLE_AI_API_KEY
# - TELEGRAM_BOT_TOKEN (optional)
# - DISCORD_WEBHOOK_URL (optional)
# - FIRECRAWL_API_URL

# Cron triggers
# These values should match those in src/config/constants.ts
[triggers]
crons = [
    # Run the orchestrator every 5 minutes to check all tasks
    "*/5 * * * *",
]

# enable logs
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
