#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Capture the list of currently staged files.
STAGED_FILES=$(git diff --cached --name-only)

# Run your formatting command.
npm run format

# Re-add only the originally staged files.
if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi
